from playwright.async_api import async_playwright
from datetime import datetime, timezone
from jinja2 import Environment, select_autoescape

PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
        .header { border-bottom: 2px solid #0891B2; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 28px; font-weight: bold; color: #0891B2; }
        .trip-info { display: flex; gap: 20px; margin-bottom: 30px; font-size: 14px; color: #666; }
        .day { margin-bottom: 40px; }
        .day-header { font-size: 20px; font-weight: bold; margin-bottom: 15px; color: #111; border-left: 4px solid #0891B2; padding-left: 10px; }
        .activity { margin-bottom: 15px; padding-left: 20px; position: relative; }
        .activity-time { font-weight: bold; font-size: 12px; color: #0891B2; }
        .activity-name { font-weight: bold; margin: 5px 0; }
        .activity-desc { font-size: 13px; color: #555; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ title or 'Your Trip Itinerary' }}</div>
        <p>Generated by Watchout</p>
    </div>
    
    <div class="trip-info">
        <span>📍 {{ cities|join(', ') }}</span>
        <span>📅 {{ start_date or 'Dates TBD' }}</span>
        <span>👥 {{ num_travelers }} Traveler(s)</span>
    </div>

    {% for day in itinerary.days %}
    {% set day_activities = day.activities if day.activities is defined else day.stops %}
    <div class="day">
        <div class="day-header">Day {{ day.day_number }}: {{ day.city }}</div>
        {% for activity in day_activities %}
        <div class="activity">
            <div class="activity-time">{{ activity.time or activity.arrival_time or '' }}</div>
            <div class="activity-name">{{ activity.name }}</div>
            <div class="activity-desc">{{ activity.description }}</div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}

    <div class="footer">
        &copy; {{ current_year }} Watchout AI. All rights reserved.
    </div>
</body>
</html>
"""

class PDFGenerator:
    @staticmethod
    async def generate_itinerary_pdf(trip_data: dict) -> bytes:
        """Generate a PDF from trip itinerary data."""
        # Auto-escape dynamic values to prevent HTML/script injection from itinerary text.
        template = Environment(
            autoescape=select_autoescape(default=True),
        ).from_string(PDF_TEMPLATE)
        html_content = template.render({
            **trip_data,
            "current_year": datetime.now(timezone.utc).year
        })
        
        async with async_playwright() as p:
            browser = await p.chromium.launch(args=['--no-sandbox'])
            page = await browser.new_page()
            await page.set_content(html_content)
            
            pdf = await page.pdf(
                format='A4',
                print_background=True,
                margin={'top': '40px', 'right': '40px', 'bottom': '40px', 'left': '40px'}
            )
            
            await browser.close()
            return pdf

itinerary_pdf_service = PDFGenerator()
