"""Central prompt builders for Watchout."""

from app.prompts.architecture import (
    RESPONSE_FORMAT_TEMPLATES,
    build_base_system_prompt,
    build_clarification_extraction_prompt,
    build_food_general_prompt,
    build_food_specialties_prompt,
    build_itinerary_parser_prompt,
    build_itinerary_prompt,
    build_mcp_server_instructions,
    build_reviewer_input_prompt,
    build_reviewer_itinerary_prompt,
    build_reviewer_output_prompt,
    build_route_regeneration_prompt,
    build_screenshot_vision_prompt,
    build_stay_general_prompt,
    build_stay_recommendations_prompt,
    build_structured_output_suffix,
    build_supervisor_planning_prompt,
    build_supervisor_smalltalk_prompt,
    build_supervisor_weaver_prompt,
    build_transport_general_prompt,
    build_transport_recommendations_prompt,
    build_trip_title_prompt,
    build_weather_general_prompt,
    build_weather_narrative_prompt,
)

__all__ = [
    "RESPONSE_FORMAT_TEMPLATES",
    "build_base_system_prompt",
    "build_structured_output_suffix",
    "build_clarification_extraction_prompt",
    "build_itinerary_prompt",
    "build_route_regeneration_prompt",
    "build_weather_general_prompt",
    "build_weather_narrative_prompt",
    "build_transport_recommendations_prompt",
    "build_transport_general_prompt",
    "build_stay_recommendations_prompt",
    "build_stay_general_prompt",
    "build_food_general_prompt",
    "build_food_specialties_prompt",
    "build_reviewer_input_prompt",
    "build_reviewer_output_prompt",
    "build_reviewer_itinerary_prompt",
    "build_supervisor_planning_prompt",
    "build_supervisor_weaver_prompt",
    "build_supervisor_smalltalk_prompt",
    "build_itinerary_parser_prompt",
    "build_screenshot_vision_prompt",
    "build_trip_title_prompt",
    "build_mcp_server_instructions",
]
